### ISSUE TITLE
Usage in a browser

### ISSUE THREAD

**Issue by rogierschouten** [artifacthealth/tsreflect#1]
Great idea, tsreflect! We were just about to invent the wheel ourselves. 
I'd like to use tsreflect in a browser with browserify. For that scenario, I'd have to be able to load JSON data from strings instead of from files/modules. Something to add maybe?

**Comment by meirgottlieb** [comment]
I haven't used browserify before. Some of the features (like createInstance) require being able to find the JS module that corresponds to the .d.json files. Any thoughts on how that would work? Could you tell me a bit more about how you plan on using it so I can think about how loading from a string would fit in? There are also references to the built-in node modules, like 'fs' and 'process'. Is that a problem? Thanks.

**Comment by rogierschouten** [comment]
The use case is simply examining the JSON in a handy way to make a run-time type check for data sent from server to client. In other words, there is no instantiation and no loading of modules should be required. 

That said, loading of modules is entirely possible if done through require(). Even e.g. 'fs' has its browserified version. 

Maybe this is outside the scope of tsreflect or maybe tsreflect could be split into two modules: one for sec JSON symbol inspection and another the more intelligent work (which is likely to differ between use cases anyway)

**Comment by meirgottlieb** [comment]
The JSON declaration can include references and require statements. How would you see those being handled in the initial data was loaded directly via a string (or JSON)?

Thanks,
Meir

**Comment by rogierschouten** [comment]
My use case has a number of simplifications, but I can see how this could be implemented in general. 

First, the simple use case: Since the data is communicated through json over http, there are only interfaces, basic types, enums and arrays  (and the orthogonal combination of these). Furthermore, I'm assuming that all type names are unique. Given that, I can just read in a bunch of .json files beforehand and find the types I need without complex dereferencing of require statements etc.  
In fact, I'm almost done with a function that does exactly that and checks incoming data for type adherance. 

However, I still think the general case can be handled if the JSON data included a "path" member for each JSON object. Then you could implement full-blown module loading semantics. Simply hand an array of all JSON 'files' to tsreflect.

**Comment by meirgottlieb** [comment]
Are you just using the .d.json files directly?

**Comment by rogierschouten** [comment]
Yes I currently am.

**Comment by meirgottlieb** [comment]
That’s probably the best thing to do. The tsreflect module is probably a bit heavyweight to use on the client anyways.

**Comment by rogierschouten** [comment]
I think you are right, that's why I was on about splitting tsreflect up into two modules. If one could split the search functions from the instantiation then users of tsreflect would become less dependent on the actual JSON format used since they would query the data with functions. This could then also include better require() resolving with path members. 

But maybe this is all getting out of scope. It seems we've reached an understanding. 
Feel free to close this issue or leave it open to see if we can get more input, I'm fine for now, thank you.
